feeds:
  # 政治・経済
  - https://news.google.com/rss/headlines/section/topic/NATION?hl=ja&gl=JP&ceid=JP:ja
  - https://news.google.com/rss/headlines/section/topic/BUSINESS?hl=ja&gl=JP&ceid=JP:ja

  # セキュリティ
  - http://www.jpcert.or.jp/rss/jpcert.rdf
  - http://jvn.jp/rss/jvnJP.rdf

  # テック
  - http://gigazine.net/index.php?/news/rss_2.0/
  - https://news.ycombinator.com/rss
  - http://qiita.com/popular-items/feed
  - http://zenn.dev/feed
